/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import DbObjects.BookCopies;
import gcitapp1.DbQueries;
import gcitapp1.TablesColumns;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Ahmed
 */
public class LibrarianPanel extends javax.swing.JPanel implements ActionListener{
    private int branchId;
    private String branchName;
    private int numBookCopies;
    private String branchAddress;
    private int bookId;
    private DbQueries dbQueries;
    private TableEnum currentTable;
    /**
     * Creates new form LibrarianPanel
     */
    public LibrarianPanel(DbQueries query) {
        initComponents();
        branchId=1;
        branchName = "Sharpstown";
        dbQueries = query; 
        currentTable = TableEnum.BOOKCOPIES;
        run();
    }
    
    public void run(){
        setListeners();
        setBookCopiesTable();
    }
    
    public void setBookCopiesTable(){
        this.jTable1.setModel(getBookCopiesTable().getModel());
    }
    public void setLibraryInfoTable(){
        this.jTable1.setModel(getLibraryInfoTable().getModel());
    }
    public JTable getBookCopiesTable(){
        TablesColumns columns= new TablesColumns();
        return columns.selectBookCopiesInBranch(getDbQueries(),getBranchName());
    }
    
    public JTable getLibraryInfoTable(){
        TablesColumns columns= new TablesColumns();
        return columns.selectLibrarianBranch(getDbQueries(),getBranchName());
    }
    public void reset(){
        setBookCopiesTable();
        cleanUp();
    }   
    public void cleanUp(){
        txt_BookCopiesNum.setText("");
        txt_branchAddress.setText("");
        txt_branchName.setText("");
    }
    public void setListeners(){    
        this.btn_TableBooks.addActionListener(this);
        this.btn_TableLibrary.addActionListener(this);
        this.btn_UpdateBookCopies.addActionListener(this);
        this.btn_UpdateLibraryInfo.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == btn_TableBooks){  
            setCurrentTable(TableEnum.BOOKCOPIES);
            cleanUp();
            setBookCopiesTable();
        }
        if(e.getSource() == btn_TableLibrary){
            setCurrentTable(TableEnum.LIBRARYINFO);
            cleanUp();
            setLibraryInfoTable();
        }  
        if(e.getSource() == btn_UpdateBookCopies){
            setNumBookCopies(Integer.valueOf(txt_BookCopiesNum.getText()));
            System.out.println(getBookId() + ", " +getBranchId() +", "+ getNumBookCopies());
            getDbQueries().setBookCopiesNum(getBookId(), getBranchId(), getNumBookCopies());
            setBookCopiesTable();
        }  
        if(e.getSource() == btn_UpdateLibraryInfo){
            System.out.println("branchID= "+getBranchId()+" branchAddress= "+getBranchName());
            setBranchName(txt_branchName.getText());
            setBranchAddress(txt_branchAddress.getText());
            getDbQueries().setBranchInfo(getBranchId(), getBranchName(), branchAddress);
            setLibraryInfoTable();
        }  
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_TableBooks = new javax.swing.JButton();
        btn_TableLibrary = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_branchName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_branchAddress = new javax.swing.JTextField();
        btn_UpdateLibraryInfo = new javax.swing.JButton();
        panel_NumCopiesUpdate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_BookCopiesNum = new javax.swing.JTextField();
        btn_UpdateBookCopies = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        btn_TableBooks.setText("Books");
        btn_TableBooks.setFocusable(false);
        btn_TableBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_TableBooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_TableBooks);

        btn_TableLibrary.setText("Library");
        btn_TableLibrary.setFocusable(false);
        btn_TableLibrary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_TableLibrary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_TableLibrary);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Branch Name");

        jLabel3.setText("Branch Address");

        btn_UpdateLibraryInfo.setText("Update");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_branchName, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txt_branchAddress)
                    .addComponent(btn_UpdateLibraryInfo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_branchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_branchAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_UpdateLibraryInfo)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jLabel1.setText("Number of Copies");

        btn_UpdateBookCopies.setText("Update");

        javax.swing.GroupLayout panel_NumCopiesUpdateLayout = new javax.swing.GroupLayout(panel_NumCopiesUpdate);
        panel_NumCopiesUpdate.setLayout(panel_NumCopiesUpdateLayout);
        panel_NumCopiesUpdateLayout.setHorizontalGroup(
            panel_NumCopiesUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NumCopiesUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panel_NumCopiesUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_UpdateBookCopies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_BookCopiesNum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_NumCopiesUpdateLayout.setVerticalGroup(
            panel_NumCopiesUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NumCopiesUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_NumCopiesUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_BookCopiesNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_UpdateBookCopies)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_NumCopiesUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_NumCopiesUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = this.jTable1.getSelectedRow();
        TableModel model = this.jTable1.getModel();
        if(getCurrentTable().equals(TableEnum.BOOKCOPIES)){
            txt_BookCopiesNum.setText(model.getValueAt(index, 3).toString());
            setNumBookCopies(Integer.valueOf(txt_BookCopiesNum.getText()));            
            setBookId(Integer.valueOf(model.getValueAt(index, 0).toString()));
        }
        if(getCurrentTable().equals(TableEnum.LIBRARYINFO)){
            txt_branchName.setText(model.getValueAt(index, 1).toString());
            txt_branchAddress.setText(model.getValueAt(index, 2).toString());
            setBranchName(txt_branchName.getText());
            setBranchAddress(txt_branchAddress.getText());
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TableBooks;
    private javax.swing.JButton btn_TableLibrary;
    private javax.swing.JButton btn_UpdateBookCopies;
    private javax.swing.JButton btn_UpdateLibraryInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panel_NumCopiesUpdate;
    private javax.swing.JTextField txt_BookCopiesNum;
    private javax.swing.JTextField txt_branchAddress;
    private javax.swing.JTextField txt_branchName;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTable1
     */
    public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    /**
     * @param jTable1 the jTable1 to set
     */
    public void setjTable1(javax.swing.JTable jTable1) {
        this.jTable1 = jTable1;
    }

    /**
     * @return the txt_BookCopiesNum
     */
    public javax.swing.JTextField getTxt_BookCopiesNum() {
        return txt_BookCopiesNum;
    }

    /**
     * @param txt_BookCopiesNum the txt_BookCopiesNum to set
     */
    public void setTxt_BookCopiesNum(javax.swing.JTextField txt_BookCopiesNum) {
        this.txt_BookCopiesNum = txt_BookCopiesNum;
    }

    /**
     * @return the txt_branchAddress
     */
    public javax.swing.JTextField getTxt_branchAddress() {
        return txt_branchAddress;
    }

    /**
     * @param txt_branchAddress the txt_branchAddress to set
     */
    public void setTxt_branchAddress(javax.swing.JTextField txt_branchAddress) {
        this.txt_branchAddress = txt_branchAddress;
    }

    /**
     * @return the txt_branchName
     */
    public javax.swing.JTextField getTxt_branchName() {
        return txt_branchName;
    }

    /**
     * @param txt_branchName the txt_branchName to set
     */
    public void setTxt_branchName(javax.swing.JTextField txt_branchName) {
        this.txt_branchName = txt_branchName;
    }

    /**
     * @return the btn_UpdateBookCopies
     */
    public javax.swing.JButton getBtn_UpdateBookCopies() {
        return btn_UpdateBookCopies;
    }

    /**
     * @param btn_UpdateBookCopies the btn_UpdateBookCopies to set
     */
    public void setBtn_UpdateBookCopies(javax.swing.JButton btn_UpdateBookCopies) {
        this.btn_UpdateBookCopies = btn_UpdateBookCopies;
    }

    /**
     * @return the btn_UpdateLibraryInfo
     */
    public javax.swing.JButton getBtn_UpdateLibraryInfo() {
        return btn_UpdateLibraryInfo;
    }

    /**
     * @param btn_UpdateLibraryInfo the btn_UpdateLibraryInfo to set
     */
    public void setBtn_UpdateLibraryInfo(javax.swing.JButton btn_UpdateLibraryInfo) {
        this.btn_UpdateLibraryInfo = btn_UpdateLibraryInfo;
    }

    /**
     * @return the branchId
     */
    public int getBranchId() {
        return branchId;
    }

    /**
     * @param branchId the branchId to set
     */
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    /**
     * @return the dbQueries
     */
    public DbQueries getDbQueries() {
        return dbQueries;
    }

    /**
     * @param dbQueries the dbQueries to set
     */
    public void setDbQueries(DbQueries dbQueries) {
        this.dbQueries = dbQueries;
    }

    /**
     * @return the branchName
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * @param branchName the branchName to set
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * @return the currentTable
     */
    public TableEnum getCurrentTable() {
        return currentTable;
    }

    /**
     * @param currentTable the currentTable to set
     */
    public void setCurrentTable(TableEnum currentTable) {
        this.currentTable = currentTable;
    }

    /**
     * @return the numBookCopies
     */
    public int getNumBookCopies() {
        return numBookCopies;
    }

    /**
     * @param numBookCopies the numBookCopies to set
     */
    public void setNumBookCopies(int numBookCopies) {
        this.numBookCopies = numBookCopies;
    }

    /**
     * @return the branchAddress
     */
    public String getBranchAddress() {
        return branchAddress;
    }

    /**
     * @param branchAddress the branchAddress to set
     */
    public void setBranchAddress(String branchAddress) {
        this.branchAddress = branchAddress;
    }

    /**
     * @return the bookId
     */
    public int getBookId() {
        return bookId;
    }

    /**
     * @param bookId the bookId to set
     */
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }
}
