/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import DbObjects.LibraryBranch;
import gcitapp1.DbQueries;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author Ahmed
 */
public class LoginPanel extends javax.swing.JPanel implements ActionListener{
    private DbQueries dbQueries;
    private int branchId;
    private String branchName;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(DbQueries query) {
        initComponents();
        dbQueries = query;
        run();
    }
    public void run(){
        setBranch();
        setListeners();
    }
    public void reset(){
        setBranch();
    }
    public void setListeners(){
        this.cb_Branches.addActionListener(this);
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == cb_Branches){  
            if(cb_Branches.getItemCount() == 0)
                setBranch();
            LibraryBranch branch = (LibraryBranch) cb_Branches.getSelectedItem();
            setBranchId(branch.getId());
            setBranchName(branch.getBranchName());
        }
    }
    public void setBranch(){
        if(cb_Branches.getItemCount()>0)
            cb_Branches.removeAllItems();
        ArrayList<LibraryBranch> branches = getDbQueries().getBranches();
        for(LibraryBranch branch: branches){
            cb_Branches.addItem(new LibraryBranch(branch.getId(), branch.getBranchName(),""));
        }
        //cb_Branches.setSelectedIndex(0);
        LibraryBranch branch = (LibraryBranch) cb_Branches.getSelectedItem();
        setBranchId(branch.getId());
        setBranchName(branch.getBranchName());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_BorrowerScreen = new javax.swing.JButton();
        btn_LibrarianScreen = new javax.swing.JButton();
        btn_AdminScreen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_borrowerId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_Branches = new javax.swing.JComboBox();

        btn_BorrowerScreen.setText("Borrower");

        btn_LibrarianScreen.setText("Librarian");

        btn_AdminScreen.setText("Admin");

        jLabel1.setText("Library Id");

        jLabel2.setText("Select Branch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_BorrowerScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LibrarianScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_AdminScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_Branches, 0, 79, Short.MAX_VALUE)
                    .addComponent(txt_borrowerId))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BorrowerScreen)
                    .addComponent(jLabel1)
                    .addComponent(txt_borrowerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LibrarianScreen)
                    .addComponent(jLabel2)
                    .addComponent(cb_Branches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_AdminScreen)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AdminScreen;
    private javax.swing.JButton btn_BorrowerScreen;
    private javax.swing.JButton btn_LibrarianScreen;
    private javax.swing.JComboBox cb_Branches;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_borrowerId;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btn_AdminScreen
     */
    public javax.swing.JButton getBtn_AdminScreen() {
        return btn_AdminScreen;
    }

    /**
     * @param btn_AdminScreen the btn_AdminScreen to set
     */
    public void setBtn_AdminScreen(javax.swing.JButton btn_AdminScreen) {
        this.btn_AdminScreen = btn_AdminScreen;
    }

    /**
     * @return the btn_BorrowerScreen
     */
    public javax.swing.JButton getBtn_BorrowerScreen() {
        return btn_BorrowerScreen;
    }

    /**
     * @param btn_BorrowerScreen the btn_BorrowerScreen to set
     */
    public void setBtn_BorrowerScreen(javax.swing.JButton btn_BorrowerScreen) {
        this.btn_BorrowerScreen = btn_BorrowerScreen;
    }

    /**
     * @return the btn_LibrarianScreen
     */
    public javax.swing.JButton getBtn_LibrarianScreen() {
        return btn_LibrarianScreen;
    }

    /**
     * @param btn_LibrarianScreen the btn_LibrarianScreen to set
     */
    public void setBtn_LibrarianScreen(javax.swing.JButton btn_LibrarianScreen) {
        this.btn_LibrarianScreen = btn_LibrarianScreen;
    }

    /**
     * @return the txt_borrowerId
     */
    public javax.swing.JTextField getTxt_borrowerId() {
        return txt_borrowerId;
    }

    /**
     * @param txt_borrowerId the txt_borrowerId to set
     */
    public void setTxt_borrowerId(javax.swing.JTextField txt_borrowerId) {
        this.txt_borrowerId = txt_borrowerId;
    }

    /**
     * @return the cb_Branches
     */
    public javax.swing.JComboBox<String> getCb_Branches() {
        return cb_Branches;
    }

    /**
     * @param cb_Branches the cb_Branches to set
     */
    public void setCb_Branches(javax.swing.JComboBox<String> cb_Branches) {
        this.cb_Branches = cb_Branches;
    }

    /**
     * @return the dbQueries
     */
    public DbQueries getDbQueries() {
        return dbQueries;
    }

    /**
     * @param dbQueries the dbQueries to set
     */
    public void setDbQueries(DbQueries dbQueries) {
        this.dbQueries = dbQueries;
    }

    /**
     * @return the branchId
     */
    public int getBranchId() {
        return branchId;
    }

    /**
     * @param branchId the branchId to set
     */
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    /**
     * @return the branchName
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * @param branchName the branchName to set
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
}
